<?php

namespace Vgplay\Games\Database\Seeders;

use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GameSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        DB::table('games')->insert(
            [
                [
                    'game_id' => 37,
                    'name' => 'Tam Giới Anh Hùng',
                    'alias' => 'tgah',
                    'banner' => 'https://img.vgplay.vn/vgplay/images/99b98961e7dce8752a7e6ad311e6eb6b.webp',
                    'favicon' => 'https://img.vgplay.vn/vgplay/images/c7542e726e9a934f12510f186e2efc7b-3.webp',
                    'icon' => 'https://img.vgplay.vn/vgplay/images/37ea7a0ffbd9cf68069763ccc64e978d.webp',
                    'logo' => 'https://img.vgplay.vn/vgplay/images/37ea7a0ffbd9cf68069763ccc64e978d.webp',
                    'thumb' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'bg_detail' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'status' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 42,
                    'name' => 'Song Kiếm Loạn Vũ',
                    'alias' => 'songkiem',
                    'banner' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'favicon' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'icon' => 'https://img.vgplay.vn/vgplay/images/83caf651ba9adfcfa65059e9e5aaa464.webp',
                    'logo' => 'https://img.vgplay.vn/vgplay/images/83caf651ba9adfcfa65059e9e5aaa464.webp',
                    'thumb' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'bg_detail' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'status' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 72,
                    'name' => 'Mộng Kiếm Tiêu Dao',
                    'alias' => 'mongkiem',
                    'banner' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'favicon' => 'https://img.vgplay.vn/vgplay/images/02898db1117f7613c101c1cb76e9288f.png',
                    'icon' => 'https://img.vgplay.vn/vgplay/images/7a52c02b0ccb2819df402a3a5bab298d.webp',
                    'logo' => 'https://img.vgplay.vn/vgplay/images/7a52c02b0ccb2819df402a3a5bab298d.webp',
                    'thumb' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'bg_detail' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'status' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 79,
                    'name' => 'Lăng Vân Chi Kiếm',
                    'alias' => 'lvck',
                    'banner' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'favicon' => 'https://img.vgplay.vn/vgplay/images/3c12d56f860f07b47ef790ef9961c5da.png',
                    'icon' => 'https://img.vgplay.vn/vgplay/images/5c03c10ba37e66618beb0328336d0412.webp',
                    'logo' => 'https://img.vgplay.vn/vgplay/images/5c03c10ba37e66618beb0328336d0412.webp',
                    'thumb' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'bg_detail' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'status' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 87,
                    'name' => 'Đấu Hồn Sư',
                    'alias' => 'dauhonsu',
                    'banner' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'favicon' => 'https://img.vgplay.vn/vgplay/images/1975a02a4431c3dccfe632de4968b8e7.png',
                    'icon' => 'https://img.vgplay.vn/vgplay/images/792a1c4a8d19232760f6ec37fc1fbec2.webp',
                    'logo' => 'https://img.vgplay.vn/vgplay/images/792a1c4a8d19232760f6ec37fc1fbec2.webp',
                    'thumb' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'bg_detail' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'status' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 81,
                    'name' => 'Linh Kiếm Chi Mộng',
                    'alias' => 'lkcm',
                    'banner' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'favicon' => 'https://img.vgplay.vn/vgplay/images/9b4babdfbee2d6d02f89ed93660cfad5.png',
                    'icon' => 'https://img.vgplay.vn/vgplay/images/696316989830190be36e2d7ad58c55c9.webp',
                    'logo' => 'https://img.vgplay.vn/vgplay/images/696316989830190be36e2d7ad58c55c9.webp',
                    'thumb' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'bg_detail' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'status' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 85,
                    'name' => 'Long Hồn Kỷ Nguyên',
                    'alias' => 'lhkn',
                    'banner' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'favicon' => 'https://img.vgplay.vn/vgplay/images/2d2fae761a8d93cd7163dfd64e36168e.png',
                    'icon' => 'https://img.vgplay.vn/vgplay/images/467239eb67683b7ddd660f485c28663d.webp',
                    'logo' => 'https://img.vgplay.vn/vgplay/images/467239eb67683b7ddd660f485c28663d.webp',
                    'thumb' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'bg_detail' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'status' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 88,
                    'name' => 'Kiếm Khách Phong Lăng',
                    'alias' => 'kkpl',
                    'banner' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'favicon' => 'https://img.vgplay.vn/vgplay/images/be6d8dfa0cf5c5bfc9d0205723d9f852.png',
                    'icon' => 'https://img.vgplay.vn/vgplay/images/9a50f8d468dda3f9419110be3f391c3b.webp',
                    'logo' => 'https://img.vgplay.vn/vgplay/images/9a50f8d468dda3f9419110be3f391c3b.webp',
                    'thumb' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'bg_detail' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'status' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 91,
                    'name' => 'Thức Thần Ký',
                    'alias' => 'ttk',
                    'banner' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'favicon' => 'https://img.vgplay.vn/vgplay/images/7364a48d37eb7acce8f357228d4fa082.webp',
                    'icon' => 'https://img.vgplay.vn/vgplay/images/01b1f803304f7a50316c81fe41a566af.webp',
                    'logo' => 'https://img.vgplay.vn/vgplay/images/01b1f803304f7a50316c81fe41a566af.webp',
                    'thumb' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'bg_detail' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'status' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 90,
                    'name' => 'Manga Bá Cháy',
                    'alias' => 'mangabachay',
                    'banner' => '',
                    'favicon' => 'https://img.vgplay.vn/vgplay/images/7364a48d37eb7acce8f357228d4fa082.webp',
                    'icon' => 'https://img.vgplay.vn/vgplay/images/38646179bccf076fa2d038a7e44a1aa9.webp',
                    'logo' => 'https://img.vgplay.vn/vgplay/images/38646179bccf076fa2d038a7e44a1aa9.webp',
                    'thumb' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'bg_detail' => 'https://img.vgplay.vn/vgplay/images/7282caf5bb222de9e0afd4bfcf539b98.png',
                    'status' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

            ]
        );

        DB::table('game_admins')->insert([
            [
                'game_id' => 37,
                'name' => 'Vy Vy',
                'desc' => 'CSKH VIP',
                'avatar' => 'https://img.vgplay.vn/vgplay/images/2387057ad1aceefcb1dba93f9041d2e1.webp',
                'facebook_url' => 'https://www.facebook.com/adsansan2510',
                'zalo_url' => 'https://img.vgplay.vn/vgplay/yeulinhgioi/images/VP/screenshot_1703836696.png',
                'telegram' => '',
                'phone' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 42,
                'name' => 'San San',
                'desc' => 'CSKH VIP',
                'avatar' => 'https://img.vgplay.vn/vgplay/images/caf45c4ba6c3665d93fa5491dbd4df1f.webp',
                'facebook_url' => 'https://www.facebook.com/SongKiemLoanVuVGP',
                'zalo_url' => 'https://img.vgplay.vn/vgplay/images/50ef30ae30cb8fb21d60a7db8090d404.webp',
                'telegram' => '',
                'phone' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 72,
                'name' => 'Băng Băng',
                'desc' => 'CSKH VIP',
                'avatar' => 'https://img.vgplay.vn/vgplay/images/08b21017c6625fbc10fc7a009a7d91be.webp',
                'facebook_url' => 'https://www.facebook.com/bangbangvgp/',
                'zalo_url' => 'https://img.vgplay.vn/vgplay/images/115e7d74a5be7f08a073a8e534942697.webp',
                'telegram' => '',
                'phone' => '0944588741',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 79,
                'name' => 'San San',
                'desc' => 'CSKH VIP',
                'avatar' => 'https://img.vgplay.vn/vgplay/images/caf45c4ba6c3665d93fa5491dbd4df1f.webp',
                'facebook_url' => 'https://www.facebook.com/SongKiemLoanVuVGP',
                'zalo_url' => 'https://img.vgplay.vn/vgplay/images/50ef30ae30cb8fb21d60a7db8090d404.webp',
                'telegram' => '',
                'phone' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 87,
                'name' => 'Băng Băng',
                'desc' => 'CSKH VIP',
                'avatar' => 'https://img.vgplay.vn/vgplay/images/08b21017c6625fbc10fc7a009a7d91be.webp',
                'facebook_url' => 'https://www.facebook.com/bangbangvgp/',
                'zalo_url' => 'https://img.vgplay.vn/vgplay/images/115e7d74a5be7f08a073a8e534942697.webp',
                'telegram' => '',
                'phone' => '0944588741',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 81,
                'name' => 'Băng Băng',
                'desc' => 'CSKH VIP',
                'avatar' => 'https://img.vgplay.vn/vgplay/images/08b21017c6625fbc10fc7a009a7d91be.webp',
                'facebook_url' => 'https://www.facebook.com/bangbangvgp/',
                'zalo_url' => 'https://img.vgplay.vn/vgplay/images/115e7d74a5be7f08a073a8e534942697.webp',
                'telegram' => '',
                'phone' => '0944588741',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 85,
                'name' => 'Băng Băng',
                'desc' => 'CSKH VIP',
                'avatar' => 'https://img.vgplay.vn/vgplay/images/08b21017c6625fbc10fc7a009a7d91be.webp',
                'facebook_url' => 'https://www.facebook.com/bangbangvgp/',
                'zalo_url' => 'https://img.vgplay.vn/vgplay/images/115e7d74a5be7f08a073a8e534942697.webp',
                'telegram' => '',
                'phone' => '0944588741',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 88,
                'name' => 'San San',
                'desc' => 'CSKH VIP',
                'avatar' => 'https://img.vgplay.vn/vgplay/images/caf45c4ba6c3665d93fa5491dbd4df1f.webp',
                'facebook_url' => 'https://www.facebook.com/SongKiemLoanVuVGP',
                'zalo_url' => 'https://img.vgplay.vn/vgplay/images/50ef30ae30cb8fb21d60a7db8090d404.webp',
                'telegram' => '',
                'phone' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 90,
                'name' => 'Vy Vy',
                'desc' => 'CSKH VIP',
                'avatar' => 'https://img.vgplay.vn/vgplay/images/2387057ad1aceefcb1dba93f9041d2e1.webp',
                'facebook_url' => 'https://www.facebook.com/adsansan2510',
                'zalo_url' => 'https://img.vgplay.vn/vgplay/yeulinhgioi/images/VP/screenshot_1703836696.png',
                'telegram' => '',
                'phone' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 91,
                'name' => 'Vân Nhi',
                'desc' => 'CSKH VIP',
                'avatar' => 'https://img.vgplay.vn/vgplay/images/379ce884a0d904cfc9ea3a263d8166b1.webp',
                'facebook_url' => 'https://www.facebook.com/linh.nguyenthuy43/h',
                'zalo_url' => 'https://img.vgplay.vn/vgplay/images/73a6283433d940757a3e46d1089f48bb.webp',
                'telegram' => '',
                'phone' => '',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        DB::table('game_apis')->insert(
            [
                [
                    'game_id' => 37,
                    'api_config' => json_encode([
                        [
                            'type' => 'servers',
                            'url' => 'https://api.example.com/servers',
                            'method' => 'GET',
                            'params' => [
                                ['key' => 'vgp_id', 'value' => 'vgp_id'],
                                ['key' => 'timestamp', 'value' => 'timestamp'],
                                ['key' => 'md5', 'value' => 'md5'],
                            ],
                        ],
                        [
                            'type' => 'roles',
                            'url' => 'https://api.example.com/roles',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgp_id', 'value' => 'vgp_id'],
                                ['key' => 'timestamp', 'value' => 'timestamp'],
                                ['key' => 'md5', 'value' => 'md5'],
                            ],
                        ],
                        [
                            'type' => 'payments',
                            'url' => 'https://api.example.com/payments',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgpid', 'value' => 'vgpid'],
                                ['key' => 'server_id', 'value' => 'server_id'],
                                ['key' => 'role_id', 'value' => 'role_id'],
                                ['key' => 'item_id', 'value' => 'item_id'],
                                ['key' => 'timestamp', 'value' => 'tstamp'],
                                ['key' => 'ticket', 'value' => 'ticket'],
                            ],
                        ],
                        [
                            'type' => 'giftcodes',
                            'url' => 'https://api.example.com/giftcodes',
                            'method' => 'GET',
                            'params' => [],
                        ],
                    ]),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'game_id' => 42,
                    'api_config' => json_encode([
                        [
                            'type' => 'servers',
                            'url' => 'http://uc-42.vgplay.vn/api.php?s=MmoChannel/listServer',
                            'method' => 'GET',
                            'params' => [],
                        ],
                        [
                            'type' => 'characters',
                            'url' => 'http://uc-42.vgplay.vn/api.php?s=MmoChannel/getRole',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgp_id', 'value' => 'vgpid'],
                                ['key' => 'server_id', 'value' => 'server_id'],
                            ],
                        ],
                        [
                            'type' => 'payments',
                            'url' => 'https://api.example.com/payments',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgpid', 'value' => 'vgpid'],
                                ['key' => 'server_id', 'value' => 'server_id'],
                                ['key' => 'role_id', 'value' => 'role_id'],
                                ['key' => 'item_id', 'value' => 'item_id'],
                                ['key' => 'timestamp', 'value' => 'tstamp'],
                                ['key' => 'ticket', 'value' => 'ticket'],
                            ],
                        ],
                        [
                            'type' => 'giftcodes',
                            'url' => 'https://api.example.com/giftcodes',
                            'method' => 'GET',
                            'params' => [],
                        ],
                    ]),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'game_id' => 72,
                    'api_config' => json_encode([
                        [
                            'type' => 'roles',
                            'url' => 'http://s1-72.vgplay.vn/api/long_vn.platform_rolelist.php',
                            'method' => 'GET',
                            'params' => [
                                ['key' => 'vgp_id', 'value' => 'vgp_id'],
                            ],
                        ],
                        [
                            'type' => 'payments',
                            'url' => 'http://s1-72.vgplay.vn/api/long_vn.platform_orderid.php',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgpid', 'value' => 'vgpid'],
                                ['key' => 'server_id', 'value' => 'server_id'],
                                ['key' => 'role_id', 'value' => 'role_id'],
                                ['key' => 'item_id', 'value' => 'item_id'],
                                ['key' => 'timestamp', 'value' => 'tstamp'],
                                ['key' => 'ticket', 'value' => 'ticket'],
                            ],
                            'payment_token_verify' => '9cwfhno9'
                        ],
                        [
                            'type' => 'giftcodes',
                            'url' => 'https://api.example.com/giftcodes',
                            'method' => 'GET',
                            'params' => [],
                        ],
                    ]),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'game_id' => 79,
                    'api_config' => json_encode([
                        [
                            'type' => 'roles',
                            'url' => 'https://x2vnweb.vgplay.vn:88/101-1001/api/roleList',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgp_id', 'value' => 'vgp_id'],
                                ['key' => 'timestamp', 'value' => 'timestamp'],
                            ],
                        ],
                        [
                            'type' => 'payments',
                            'url' => 'https://x2vnweb.vgplay.vn:88/101-1001/api/payToken',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgpid', 'value' => 'vgpid'],
                                ['key' => 'server_id', 'value' => 'server_id'],
                                ['key' => 'role_id', 'value' => 'role_id'],
                                ['key' => 'item_id', 'value' => 'item_id'],
                                ['key' => 'timestamp', 'value' => 'tstamp'],
                                ['key' => 'ticket', 'value' => 'ticket'],
                            ],
                            'payment_token_verify' => 'tcxwxw3yts'
                        ],
                        [
                            'type' => 'giftcodes',
                            'url' => 'https://api.example.com/giftcodes',
                            'method' => 'GET',
                            'params' => [],
                        ],
                    ]),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'game_id' => 87,
                    'api_config' => json_encode([
                        [
                            'type' => 'servers',
                            'url' => 'https://api.example.com/servers',
                            'method' => 'GET',
                            'params' => [
                                ['key' => 'vgp_id', 'value' => 'vgp_id'],
                                ['key' => 'timestamp', 'value' => 'timestamp'],
                                ['key' => 'md5', 'value' => 'md5'],
                            ],
                        ],
                        [
                            'type' => 'roles',
                            'url' => 'https://api.example.com/roles',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgp_id', 'value' => 'vgp_id'],
                                ['key' => 'timestamp', 'value' => 'timestamp'],
                                ['key' => 'md5', 'value' => 'md5'],
                            ],
                        ],
                        [
                            'type' => 'payments',
                            'url' => 'https://api.example.com/payments',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgpid', 'value' => 'vgpid'],
                                ['key' => 'server_id', 'value' => 'server_id'],
                                ['key' => 'role_id', 'value' => 'role_id'],
                                ['key' => 'item_id', 'value' => 'item_id'],
                                ['key' => 'timestamp', 'value' => 'tstamp'],
                                ['key' => 'ticket', 'value' => 'ticket'],
                            ],
                        ],
                        [
                            'type' => 'giftcodes',
                            'url' => 'https://api.example.com/giftcodes',
                            'method' => 'GET',
                            'params' => [],
                        ],
                    ]),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'game_id' => 81,
                    'api_config' => json_encode([
                        [
                            'type' => 'servers',
                            'url' => 'https://api.example.com/servers',
                            'method' => 'GET',
                            'params' => [
                                ['key' => 'vgp_id', 'value' => 'vgp_id'],
                                ['key' => 'timestamp', 'value' => 'timestamp'],
                                ['key' => 'md5', 'value' => 'md5'],
                            ],
                        ],
                        [
                            'type' => 'roles',
                            'url' => 'https://api.example.com/roles',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgp_id', 'value' => 'vgp_id'],
                                ['key' => 'timestamp', 'value' => 'timestamp'],
                                ['key' => 'md5', 'value' => 'md5'],
                            ],
                        ],
                        [
                            'type' => 'payments',
                            'url' => 'https://api.example.com/payments',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgpid', 'value' => 'vgpid'],
                                ['key' => 'server_id', 'value' => 'server_id'],
                                ['key' => 'role_id', 'value' => 'role_id'],
                                ['key' => 'item_id', 'value' => 'item_id'],
                                ['key' => 'timestamp', 'value' => 'tstamp'],
                                ['key' => 'ticket', 'value' => 'ticket'],
                            ],
                        ],
                        [
                            'type' => 'giftcodes',
                            'url' => 'https://api.example.com/giftcodes',
                            'method' => 'GET',
                            'params' => [],
                        ],
                    ]),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'game_id' => 85,
                    'api_config' => json_encode([
                        [
                            'type' => 'roles',
                            'url' => 'http://gateway-85.vgplay.vn/api/vn/get_role.php',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgp_id', 'value' => 'vgp_id'],
                                ['key' => 'timestamp', 'value' => 'timestamp'],
                            ],
                        ],
                        [
                            'type' => 'payments',
                            'url' => 'http://gateway-85.vgplay.vn/api/vn/get_ptoken.php',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgpid', 'value' => 'vgpid'],
                                ['key' => 'server_id', 'value' => 'server_id'],
                                ['key' => 'role_id', 'value' => 'role_id'],
                                ['key' => 'item_id', 'value' => 'item_id'],
                                ['key' => 'timestamp', 'value' => 'tstamp'],
                                ['key' => 'ticket', 'value' => 'ticket'],
                            ],
                            'payment_token_verify' => 'tcxwxw4yox'
                        ],
                        [
                            'type' => 'giftcodes',
                            'url' => 'https://api.example.com/giftcodes',
                            'method' => 'GET',
                            'params' => [],
                        ],
                    ]),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'game_id' => 88,
                    'api_config' => json_encode([
                        [
                            'type' => 'roles',
                            'url' => 'http://ctl-88.vgplay.vn/user/vgpQueryRole',
                            'method' => 'GET',
                            'params' => [
                                ['key' => 'vgp_id', 'value' => 'vgp_id'],
                                ['key' => 'timestamp', 'value' => 'timestamp'],
                            ],
                        ],
                        [
                            'type' => 'payments',
                            'url' => 'http://ctl-88.vgplay.vn/pay/vgpGetToken',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgpid', 'value' => 'vgpid'],
                                ['key' => 'server_id', 'value' => 'server_id'],
                                ['key' => 'role_id', 'value' => 'role_id'],
                                ['key' => 'item_id', 'value' => 'item_id'],
                                ['key' => 'timestamp', 'value' => 'tstamp'],
                                ['key' => 'ticket', 'value' => 'ticket'],
                            ],
                            'payment_token_verify' => 'kfnpux'
                        ],
                        [
                            'type' => 'giftcodes',
                            'url' => 'https://api.example.com/giftcodes',
                            'method' => 'GET',
                            'params' => [],
                        ],
                    ]),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'game_id' => 90,
                    'api_config' => json_encode([
                        [
                            'type' => 'servers',
                            'url' => 'https://api.example.com/servers',
                            'method' => 'GET',
                            'params' => [
                                ['key' => 'vgp_id', 'value' => 'vgp_id'],
                                ['key' => 'timestamp', 'value' => 'timestamp'],
                                ['key' => 'md5', 'value' => 'md5'],
                            ],
                        ],
                        [
                            'type' => 'roles',
                            'url' => 'https://api.example.com/roles',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgp_id', 'value' => 'vgp_id'],
                                ['key' => 'timestamp', 'value' => 'timestamp'],
                                ['key' => 'md5', 'value' => 'md5'],
                            ],
                        ],
                        [
                            'type' => 'payments',
                            'url' => 'https://api.example.com/payments',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgpid', 'value' => 'vgpid'],
                                ['key' => 'server_id', 'value' => 'server_id'],
                                ['key' => 'role_id', 'value' => 'role_id'],
                                ['key' => 'item_id', 'value' => 'item_id'],
                                ['key' => 'timestamp', 'value' => 'tstamp'],
                                ['key' => 'ticket', 'value' => 'ticket'],
                            ],
                        ],
                        [
                            'type' => 'giftcodes',
                            'url' => 'https://api.example.com/giftcodes',
                            'method' => 'GET',
                            'params' => [],
                        ],
                    ]),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'game_id' => 91,
                    'api_config' => json_encode([
                        [
                            'type' => 'servers',
                            'url' => 'https://api.example.com/servers',
                            'method' => 'GET',
                            'params' => [
                                ['key' => 'vgp_id', 'value' => 'vgp_id'],
                                ['key' => 'timestamp', 'value' => 'timestamp'],
                                ['key' => 'md5', 'value' => 'md5'],
                            ],
                        ],
                        [
                            'type' => 'roles',
                            'url' => 'https://api.example.com/roles',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgp_id', 'value' => 'vgp_id'],
                                ['key' => 'timestamp', 'value' => 'timestamp'],
                                ['key' => 'md5', 'value' => 'md5'],
                            ],
                        ],
                        [
                            'type' => 'payments',
                            'url' => 'https://api.example.com/payments',
                            'method' => 'POST',
                            'params' => [
                                ['key' => 'vgpid', 'value' => 'vgpid'],
                                ['key' => 'server_id', 'value' => 'server_id'],
                                ['key' => 'role_id', 'value' => 'role_id'],
                                ['key' => 'item_id', 'value' => 'item_id'],
                                ['key' => 'timestamp', 'value' => 'tstamp'],
                                ['key' => 'ticket', 'value' => 'ticket'],
                            ],
                        ],
                        [
                            'type' => 'giftcodes',
                            'url' => 'https://api.example.com/giftcodes',
                            'method' => 'GET',
                            'params' => [],
                        ],
                    ]),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );

        DB::table('game_socials')->insert(
            [
                [
                    'game_id' => 37,
                    'app_id' => '2389857334422322',
                    'app_secret' => '446eb462bae8e3db0e600b5bb3118ac4',
                    'fanpage_url' => 'https://www.facebook.com/tamgioi.vgplay.vn',
                    'group_url' => 'https://www.facebook.com/groups/tamgioianhhung',
                    'messenger_url' => 'https://m.me/2337722456462864',
                    'zalo_oa' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 42,
                    'app_id' => '2389857334422322',
                    'app_secret' => '446eb462bae8e3db0e600b5bb3118ac4',
                    'fanpage_url' => 'https://www.facebook.com/SongKiemLoanVuVGP',
                    'group_url' => 'https://www.facebook.com/groups/SongKiemLoanVuVGP/',
                    'messenger_url' => 'https://m.me/102682241455624',
                    'zalo_oa' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 72,
                    'app_id' => '2389857334422322',
                    'app_secret' => '446eb462bae8e3db0e600b5bb3118ac4',
                    'fanpage_url' => 'https://www.facebook.com/MongKiemTieuDao',
                    'group_url' => 'https://www.facebook.com/groups/mongkiemtieudao',
                    'messenger_url' => 'https://m.me/MongKiemTieuDao',
                    'zalo_oa' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 79,
                    'app_id' => '2389857334422322',
                    'app_secret' => '446eb462bae8e3db0e600b5bb3118ac4',
                    'fanpage_url' => 'https://www.facebook.com/LangVanChiKiem',
                    'group_url' => 'https://www.facebook.com/groups/langvanchikiemvgp',
                    'messenger_url' => 'https://m.me/322642380926453',
                    'zalo_oa' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 87,
                    'app_id' => '2389857334422322',
                    'app_secret' => '446eb462bae8e3db0e600b5bb3118ac4',
                    'fanpage_url' => 'https://www.facebook.com/DauHonSuVGP/',
                    'group_url' => 'https://www.facebook.com/groups/dauhonsuvgp',
                    'messenger_url' => 'https://m.me/dauhonsuvgp',
                    'zalo_oa' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 81,
                    'app_id' => '2389857334422322',
                    'app_secret' => '446eb462bae8e3db0e600b5bb3118ac4',
                    'fanpage_url' => 'https://fb.com/linhkiemchimong',
                    'group_url' => 'https://www.facebook.com/groups/linhkiemchimong.vgplay.vn',
                    'messenger_url' => 'https://m.me/linhkiemchimong',
                    'zalo_oa' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 85,
                    'app_id' => '2389857334422322',
                    'app_secret' => '446eb462bae8e3db0e600b5bb3118ac4',
                    'fanpage_url' => 'https://www.facebook.com/LongHonKyNguyen/',
                    'group_url' => 'https://www.facebook.com/groups/longhonkynguyen',
                    'messenger_url' => 'https://m.me/longhonkynguyen',
                    'zalo_oa' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 88,
                    'app_id' => '2389857334422322',
                    'app_secret' => '446eb462bae8e3db0e600b5bb3118ac4',
                    'fanpage_url' => 'https://www.facebook.com/KiemKhachPhongLang/',
                    'group_url' => 'https://www.facebook.com/groups/kiemkhachphonglangvgp/',
                    'messenger_url' => 'https://m.me/698777329980455',
                    'zalo_oa' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 90,
                    'app_id' => '1335812021199089',
                    'app_secret' => '748e87bf4793253fceef10c8fbd610f0',
                    'fanpage_url' => 'https://www.facebook.com/mangabachay.vgp',
                    'group_url' => 'https://www.facebook.com/groups/4265879100398395/',
                    'messenger_url' => 'https://www.facebook.com/messages/t/193500191213682',
                    'zalo_oa' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 91,
                    'app_id' => '2389857334422322',
                    'app_secret' => '446eb462bae8e3db0e600b5bb3118ac4',
                    'fanpage_url' => 'https://www.facebook.com/thucthanky/',
                    'group_url' => 'https://www.facebook.com/groups/1046411327647462',
                    'messenger_url' => 'https://m.me/737757479413200',
                    'zalo_oa' => '',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
            ]
        );

        DB::table('game_flags')->insert(
            [
                [
                    'game_id' => 37,
                    'flags'   => json_encode([
                        'enable_hot_game' => true,
                        'enable_new_game' => false,
                        'enable_webshop'  => false,
                        'enable_webgame'  => false,
                        'enable_open_beta' => false,
                        'check_roles'     => false,
                        'enable_buy_item' => false,
                    ], JSON_UNESCAPED_UNICODE),
                ],
                [
                    'game_id' => 42,
                    'flags'   => json_encode([
                        'enable_hot_game' => true,
                        'enable_new_game' => false,
                        'enable_webshop'  => false,
                        'enable_webgame'  => false,
                        'enable_open_beta' => false,
                        'check_roles'     => false,
                        'enable_buy_item' => false,
                    ], JSON_UNESCAPED_UNICODE),
                ],
                [
                    'game_id' => 72,
                    'flags'   => json_encode([
                        'enable_hot_game' => true,
                        'enable_new_game' => false,
                        'enable_webshop'  => false,
                        'enable_webgame'  => false,
                        'enable_open_beta' => false,
                        'check_roles'     => true,
                        'enable_buy_item' => true,
                    ], JSON_UNESCAPED_UNICODE),
                ],
                [
                    'game_id' => 79,
                    'flags'   => json_encode([
                        'enable_hot_game' => true,
                        'enable_new_game' => false,
                        'enable_webshop'  => false,
                        'enable_webgame'  => false,
                        'enable_open_beta' => false,
                        'check_roles'     => true,
                        'enable_buy_item' => true,
                    ], JSON_UNESCAPED_UNICODE),
                ],
                [
                    'game_id' => 87,
                    'flags'   => json_encode([
                        'enable_hot_game' => true,
                        'enable_new_game' => false,
                        'enable_webshop'  => false,
                        'enable_webgame'  => false,
                        'enable_open_beta' => false,
                        'check_roles'     => false,
                        'enable_buy_item' => false,
                    ], JSON_UNESCAPED_UNICODE),
                ],
                [
                    'game_id' => 81,
                    'flags'   => json_encode([
                        'enable_hot_game' => true,
                        'enable_new_game' => false,
                        'enable_webshop'  => false,
                        'enable_webgame'  => false,
                        'enable_open_beta' => false,
                        'check_roles'     => false,
                        'enable_buy_item' => false,
                    ], JSON_UNESCAPED_UNICODE),
                ],
                [
                    'game_id' => 85,
                    'flags'   => json_encode([
                        'enable_hot_game' => true,
                        'enable_new_game' => false,
                        'enable_webshop'  => false,
                        'enable_webgame'  => false,
                        'enable_open_beta' => false,
                        'check_roles'     => true,
                        'enable_buy_item' => true,
                    ], JSON_UNESCAPED_UNICODE),
                ],
                [
                    'game_id' => 88,
                    'flags'   => json_encode([
                        'enable_hot_game' => true,
                        'enable_new_game' => false,
                        'enable_webshop'  => false,
                        'enable_webgame'  => false,
                        'enable_open_beta' => false,
                        'check_roles'     => true,
                        'enable_buy_item' => true,
                    ], JSON_UNESCAPED_UNICODE),
                ],
                [
                    'game_id' => 91,
                    'flags'   => json_encode([
                        'enable_hot_game' => true,
                        'enable_new_game' => false,
                        'enable_webshop'  => false,
                        'enable_webgame'  => false,
                        'enable_open_beta' => false,
                        'check_roles'     => false,
                        'enable_buy_item' => false,
                    ], JSON_UNESCAPED_UNICODE),
                ],
                [
                    'game_id' => 90,
                    'flags'   => json_encode([
                        'enable_hot_game' => true,
                        'enable_new_game' => true,
                        'enable_webshop'  => false,
                        'enable_webgame'  => false,
                        'enable_open_beta' => false,
                        'check_roles'     => false,
                        'enable_buy_item' => false,
                    ], JSON_UNESCAPED_UNICODE),
                ],
            ]
        );

        DB::table('game_settings')->insert(
            [
                [
                    'game_id' => 37,
                    'required_vxu' => 15000000,
                    'description' => 'Tam Giới Anh Hùng là game nhập vai hấp dẫn.',
                    'content' => 'Chiến đấu với các vị thần trong thế giới huyền ảo.',
                    'homepage_url' => 'https://tgah.vgplay.vn',
                    'appstore_url' => 'https://apps.apple.com/vn/tgah',
                    'google_play_url' => 'https://play.google.com/store/apps/details?id=tgah',
                    'apk_url' => 'https://cdn.tgah.vn/download/tgah.apk',
                    'support_url' => 'https://tgah.vn/support',
                    'cdn_url' => 'https://cdn.tgah.vn',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 42,
                    'required_vxu' => 15000000,
                    'description' => 'Tam Giới Anh Hùng là game nhập vai hấp dẫn.',
                    'content' => 'Chiến đấu với các vị thần trong thế giới huyền ảo.',
                    'homepage_url' => 'https://tgah.vgplay.vn',
                    'appstore_url' => 'https://apps.apple.com/vn/tgah',
                    'google_play_url' => 'https://play.google.com/store/apps/details?id=tgah',
                    'apk_url' => 'https://cdn.tgah.vn/download/tgah.apk',
                    'support_url' => 'https://tgah.vn/support',
                    'cdn_url' => 'https://cdn.tgah.vn',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 72,
                    'required_vxu' => 15000000,
                    'description' => 'Tam Giới Anh Hùng là game nhập vai hấp dẫn.',
                    'content' => 'Chiến đấu với các vị thần trong thế giới huyền ảo.',
                    'homepage_url' => 'https://tgah.vgplay.vn',
                    'appstore_url' => 'https://apps.apple.com/vn/tgah',
                    'google_play_url' => 'https://play.google.com/store/apps/details?id=tgah',
                    'apk_url' => 'https://cdn.tgah.vn/download/tgah.apk',
                    'support_url' => 'https://tgah.vn/support',
                    'cdn_url' => 'https://cdn.tgah.vn',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 79,
                    'required_vxu' => 20000000,
                    'description' => 'Tam Giới Anh Hùng là game nhập vai hấp dẫn.',
                    'content' => 'Chiến đấu với các vị thần trong thế giới huyền ảo.',
                    'homepage_url' => 'https://tgah.vgplay.vn',
                    'appstore_url' => 'https://apps.apple.com/vn/tgah',
                    'google_play_url' => 'https://play.google.com/store/apps/details?id=tgah',
                    'apk_url' => 'https://cdn.tgah.vn/download/tgah.apk',
                    'support_url' => 'https://tgah.vn/support',
                    'cdn_url' => 'https://cdn.tgah.vn',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 87,
                    'required_vxu' => 20000000,
                    'description' => 'Tam Giới Anh Hùng là game nhập vai hấp dẫn.',
                    'content' => 'Chiến đấu với các vị thần trong thế giới huyền ảo.',
                    'homepage_url' => 'https://tgah.vgplay.vn',
                    'appstore_url' => 'https://apps.apple.com/vn/tgah',
                    'google_play_url' => 'https://play.google.com/store/apps/details?id=tgah',
                    'apk_url' => 'https://cdn.tgah.vn/download/tgah.apk',
                    'support_url' => 'https://tgah.vn/support',
                    'cdn_url' => 'https://cdn.tgah.vn',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 81,
                    'required_vxu' => 10000000,
                    'description' => 'Tam Giới Anh Hùng là game nhập vai hấp dẫn.',
                    'content' => 'Chiến đấu với các vị thần trong thế giới huyền ảo.',
                    'homepage_url' => 'https://tgah.vgplay.vn',
                    'appstore_url' => 'https://apps.apple.com/vn/tgah',
                    'google_play_url' => 'https://play.google.com/store/apps/details?id=tgah',
                    'apk_url' => 'https://cdn.tgah.vn/download/tgah.apk',
                    'support_url' => 'https://tgah.vn/support',
                    'cdn_url' => 'https://cdn.tgah.vn',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 85,
                    'required_vxu' => 10000000,
                    'description' => 'Tam Giới Anh Hùng là game nhập vai hấp dẫn.',
                    'content' => 'Chiến đấu với các vị thần trong thế giới huyền ảo.',
                    'homepage_url' => 'https://tgah.vgplay.vn',
                    'appstore_url' => 'https://apps.apple.com/vn/tgah',
                    'google_play_url' => 'https://play.google.com/store/apps/details?id=tgah',
                    'apk_url' => 'https://cdn.tgah.vn/download/tgah.apk',
                    'support_url' => 'https://tgah.vn/support',
                    'cdn_url' => 'https://cdn.tgah.vn',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 88,
                    'required_vxu' => 10000000,
                    'description' => 'Tam Giới Anh Hùng là game nhập vai hấp dẫn.',
                    'content' => 'Chiến đấu với các vị thần trong thế giới huyền ảo.',
                    'homepage_url' => 'https://tgah.vgplay.vn',
                    'appstore_url' => 'https://apps.apple.com/vn/tgah',
                    'google_play_url' => 'https://play.google.com/store/apps/details?id=tgah',
                    'apk_url' => 'https://cdn.tgah.vn/download/tgah.apk',
                    'support_url' => 'https://tgah.vn/support',
                    'cdn_url' => 'https://cdn.tgah.vn',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 90,
                    'required_vxu' => 10000000,
                    'description' => 'Tam Giới Anh Hùng là game nhập vai hấp dẫn.',
                    'content' => 'Chiến đấu với các vị thần trong thế giới huyền ảo.',
                    'homepage_url' => 'https://tgah.vgplay.vn',
                    'appstore_url' => 'https://apps.apple.com/vn/tgah',
                    'google_play_url' => 'https://play.google.com/store/apps/details?id=tgah',
                    'apk_url' => 'https://cdn.tgah.vn/download/tgah.apk',
                    'support_url' => 'https://tgah.vn/support',
                    'cdn_url' => 'https://cdn.tgah.vn',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'game_id' => 91,
                    'required_vxu' => 10000000,
                    'description' => 'Tam Giới Anh Hùng là game nhập vai hấp dẫn.',
                    'content' => 'Chiến đấu với các vị thần trong thế giới huyền ảo.',
                    'homepage_url' => 'https://tgah.vgplay.vn',
                    'appstore_url' => 'https://apps.apple.com/vn/tgah',
                    'google_play_url' => 'https://play.google.com/store/apps/details?id=tgah',
                    'apk_url' => 'https://cdn.tgah.vn/download/tgah.apk',
                    'support_url' => 'https://tgah.vn/support',
                    'cdn_url' => 'https://cdn.tgah.vn',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
            ]
        );
    }
}
